# Generated by Django 6.0.6 on 2026-06-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_delete_apppoinment"),
        ("doctors", "0002_specialization_remove_doctor_department_and_more"),
        ("medical_records", "0001_initial"),
        ("patients", "0002_healtheducationresource_remove_patient_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicalrecord",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="medications",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="treatment_plan",
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="attachments",
            field=models.FileField(blank=True, null=True, upload_to="medical_records/"),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="is_confidential",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="symptoms",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="treatment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="vital_signs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medical_records",
                to="doctors.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_records",
                to="patients.patient",
            ),
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=200)),
                ("result", models.TextField()),
                ("normal_range", models.CharField(blank=True, max_length=100)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("is_abnormal", models.BooleanField(default=False)),
                ("test_date", models.DateField()),
                (
                    "report_file",
                    models.FileField(blank=True, null=True, upload_to="lab_results/"),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="medical_records.medicalrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-test_date"],
            },
        ),
    ]
