# Generated by Django 6.0.6 on 2026-06-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_appointment_delete_apppoinment"),
        ("doctors", "0002_specialization_remove_doctor_department_and_more"),
        ("patients", "0002_healtheducationresource_remove_patient_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugInteractionWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_a", models.CharField(max_length=200)),
                ("drug_b", models.CharField(max_length=200)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "unique_together": {("drug_a", "drug_b")},
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("pharmacy_name", models.CharField(blank=True, max_length=200)),
                ("pharmacy_address", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appointments.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("dosage", models.CharField(max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once_daily", "Once Daily"),
                            ("twice_daily", "Twice Daily"),
                            ("three_times", "Three Times Daily"),
                            ("four_times", "Four Times Daily"),
                            ("as_needed", "As Needed"),
                            ("weekly", "Weekly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_days", models.PositiveIntegerField()),
                ("instructions", models.TextField(blank=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("refills_allowed", models.PositiveIntegerField(default=0)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
        ),
    ]
