# Generated by Django 5.2.6 on 2026-06-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_specialization_remove_doctor_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="consultation_fee",
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
